# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia1', models.CharField(max_length=25)),
                ('dia2', models.CharField(max_length=25)),
                ('dia3', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Aula')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reusables.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='SubNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=25)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Nivel')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reusables.SubNivel'),
        ),
    ]
