# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='unidad',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
