# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
