# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
    ]
