# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 17:50
from __future__ import unicode_literals

import apps.inicio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=100)),
                ('gradoacademico', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('paterno', apps.inicio.models.upperCharField(max_length=45)),
                ('materno', apps.inicio.models.upperCharField(max_length=45)),
                ('nombre', apps.inicio.models.upperCharField(max_length=50)),
                ('fechanacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('foto', models.ImageField(upload_to=b'')),
                ('telefono', models.CharField(blank=True, max_length=8, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoderado', to='inicio.Persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='inicio.Persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together=set([('persona', 'apoderado')]),
        ),
    ]
