# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inicio.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observacion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apoderado', to='inicio.Apoderado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='inicio.Persona', unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together=set([]),
        ),
    ]
