# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20180821_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='inicio.Persona'),
        ),
    ]
