# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20180822_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
