# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20180824_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['-id']},
        ),
    ]
